"use strict";
const state={config:null,answers:[],scores:null}; const $=s=>document.querySelector(s);
const colorHex={Rouge:'#d93b3b',Jaune:'#e5ad00',Vert:'#2d9b69',Bleu:'#2f6fc2'};
async function init(){try{const r=await fetch('data/questions.json',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);state.config=await r.json();state.answers=Array(state.config.questions.length).fill(null);render();restore()}catch(e){showError("Impossible de charger les questions. Ouvrez le projet via GitHub Pages ou un serveur local, et non directement avec file://.")}}
function render(){const box=$('#questions');state.config.questions.forEach((q,i)=>{const a=document.createElement('article');a.className='question';a.id='q'+q.id;a.innerHTML=`<div class="qhead"><span>Question ${q.id}</span><span class="badge">Non répondu</span></div><div class="choices"><div>${escapeHtml(q.left.text)}</div><div>${escapeHtml(q.right.text)}</div></div><div class="slider"><b>A</b><input type="range" min="1" max="6" step="1" value="3" data-i="${i}" aria-label="Question ${q.id}, position 1 à 6"><b>B</b></div><div class="ticks"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span></div><div class="value">Déplacez le curseur</div>`;box.appendChild(a)});box.addEventListener('input',onInput);$('#identity').addEventListener('input',save);$('#resultBtn').onclick=showResults;$('#resetBtn').onclick=reset;$('#printBtn').onclick=()=>print();$('#pdfBtn').onclick=exportPdf}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function onInput(e){if(!e.target.matches('input[type=range]'))return;const i=+e.target.dataset.i,v=+e.target.value;state.answers[i]=v;const card=e.target.closest('.question');card.classList.add('answered');card.querySelector('.badge').textContent='Répondu';card.querySelector('.value').textContent='Position '+v;progress();save()}
function progress(){const n=state.answers.filter(Number.isInteger).length;$('#progressText').textContent=`${n} / ${state.answers.length} réponses`;$('#progressFill').style.width=(100*n/state.answers.length)+'%'}
function save(){localStorage.setItem('profilCouleursV2',JSON.stringify({identity:$('#identity').value,answers:state.answers}))}
function restore(){try{const d=JSON.parse(localStorage.getItem('profilCouleursV2'));if(!d)return;$('#identity').value=d.identity||'';(d.answers||[]).forEach((v,i)=>{if(Number.isInteger(v)&&state.answers[i]!==undefined){state.answers[i]=v;const input=document.querySelector(`[data-i="${i}"]`);input.value=v;const card=input.closest('.question');card.classList.add('answered');card.querySelector('.badge').textContent='Répondu';card.querySelector('.value').textContent='Position '+v}});progress()}catch{}}
function calculate(){const s={Rouge:0,Jaune:0,Vert:0,Bleu:0},scale=state.config.scale;state.config.questions.forEach((q,i)=>{const v=state.answers[i];if(v<=3)s[q.left.color]+=scale.leftPoints[String(v)];else s[q.right.color]+=scale.rightPoints[String(v)]});return s}
function showResults(){const missing=state.answers.map((v,i)=>v===null?i+1:null).filter(Boolean);if(missing.length){showError(`Veuillez répondre aux questions : ${missing.join(', ')}.`);$('#q'+missing[0]).scrollIntoView({behavior:'smooth'});return}$('#error').style.display='none';const s=state.scores=calculate(),total=Object.values(s).reduce((a,b)=>a+b,0),rank=Object.entries(s).sort((a,b)=>b[1]-a[1]);$('#resultIdentity').textContent=$('#identity').value?`Profil de ${$('#identity').value}`:'Profil anonyme';$('#dominance').innerHTML=`Dominante : <strong style="color:${colorHex[rank[0][0]]}">${rank[0][0]}</strong> · Secondaire : <strong style="color:${colorHex[rank[1][0]]}">${rank[1][0]}</strong>`;$('#scoreGrid').innerHTML=Object.keys(s).map(k=>`<div class="score ${k}"><span>${k}</span><strong>${s[k]}</strong><small>${(100*s[k]/total).toFixed(1).replace('.',',')} %</small></div>`).join('');$('#readingText').textContent=`Le profil fait ressortir une préférence dominante ${rank[0][0]} et une tendance secondaire ${rank[1][0]}. L’écart est de ${rank[0][1]-rank[1][1]} point(s).`;drawRadar(s);$('#results').style.display='block';$('#results').scrollIntoView({behavior:'smooth'});save()}
function drawRadar(s){const c=$('#radar'),x=c.getContext('2d'),labels=Object.keys(s),cx=300,cy=300,R=205,max=90;x.clearRect(0,0,600,600);x.font='bold 22px Segoe UI';x.textAlign='center';x.textBaseline='middle';for(let z=1;z<=4;z++){x.beginPath();labels.forEach((_,i)=>{const a=-Math.PI/2+i*Math.PI/2,r=R*z/4,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.strokeStyle='#dbe4ee';x.stroke()}labels.forEach((l,i)=>{const a=-Math.PI/2+i*Math.PI/2;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);x.stroke();x.fillStyle=colorHex[l];x.fillText(l,cx+Math.cos(a)*(R+45),cy+Math.sin(a)*(R+45))});x.beginPath();labels.forEach((l,i)=>{const a=-Math.PI/2+i*Math.PI/2,r=R*s[l]/max,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.fillStyle='#2563eb2e';x.fill();x.strokeStyle='#2563eb';x.lineWidth=4;x.stroke()}
function exportPdf(){if(!state.scores){showError('Affichez d’abord votre profil.');return}if(!window.jspdf){showError('Le module PDF n’est pas disponible. Vérifiez votre connexion Internet, puis rechargez la page.');return}const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'}),name=$('#identity').value.trim()||'Anonyme',s=state.scores,total=Object.values(s).reduce((a,b)=>a+b,0),rank=Object.entries(s).sort((a,b)=>b[1]-a[1]);doc.setFillColor(23,50,77);doc.rect(0,0,210,33,'F');doc.setTextColor(255);doc.setFontSize(20);doc.text('Profil de management par les couleurs',105,15,{align:'center'});doc.setFontSize(11);doc.text(`Participant : ${name}`,105,24,{align:'center'});doc.setTextColor(30);doc.setFontSize(14);doc.text(`Dominante : ${rank[0][0]}  |  Secondaire : ${rank[1][0]}`,20,47);let y=61;Object.entries(s).forEach(([k,v])=>{const rgb={Rouge:[217,59,59],Jaune:[229,173,0],Vert:[45,155,105],Bleu:[47,111,194]}[k];doc.setFillColor(...rgb);doc.roundedRect(20,y-7,45,13,2,2,'F');doc.setTextColor(k==='Jaune'?40:255);doc.text(`${k} : ${v} (${(100*v/total).toFixed(1)} %)`,42.5,y+1,{align:'center'});y+=18});doc.addImage($('#radar').toDataURL('image/png'),'PNG',85,56,105,105);doc.setTextColor(30);doc.setFontSize(12);doc.text('Lecture pédagogique',20,148);doc.setFontSize(10);const text=`Le profil fait ressortir une préférence dominante ${rank[0][0]} et une tendance secondaire ${rank[1][0]}. L'écart entre les deux tendances est de ${rank[0][1]-rank[1][1]} point(s).`;doc.text(doc.splitTextToSize(text,170),20,157);doc.setDrawColor(200);doc.line(20,180,190,180);doc.setFontSize(9);doc.setTextColor(90);doc.text(doc.splitTextToSize("Outil pédagogique inspiré du modèle DISC / management par les couleurs. Les scores indiquent une tendance relative et ne constituent ni un diagnostic psychologique ni un test psychométrique validé.",170),20,188);doc.save(`profil-couleurs-${slug(name)}.pdf`)}
function slug(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'anonyme'}
function reset(){if(!confirm('Réinitialiser toutes les réponses ?'))return;localStorage.removeItem('profilCouleursV2');location.reload()}
function showError(m){$('#error').textContent=m;$('#error').style.display='block'}
init();