"use strict";
const S={c:null,a:[],scores:null},$=s=>document.querySelector(s),hex={Rouge:'#d93b3b',Jaune:'#e5ad00',Vert:'#2d9b69',Bleu:'#2f6fc2'};
async function init(){try{const r=await fetch('data/questions.json',{cache:'no-store'});if(!r.ok)throw 0;S.c=await r.json();S.a=Array(S.c.questions.length).fill(null);render();restore()}catch(e){err('Impossible de charger les questions. Utilisez GitHub Pages ou un serveur local.')}}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const b=$('#questions');S.c.questions.forEach((q,i)=>{const a=document.createElement('article');a.className='question';a.id='q'+q.id;const left=[1,2,3].map(v=>dot(i,v,q.id)).join(''),right=[4,5,6].map(v=>dot(i,v,q.id)).join('');a.innerHTML=`<div class="qhead"><span>Question ${q.id}</span><span class="badge">Non répondu</span></div><div class="qbody"><div class="choices"><div>${esc(q.left.text)}</div><div>${esc(q.right.text)}</div></div><div class="choice-scale"><div class="rail" aria-hidden="true"></div><div class="scale" role="group" aria-label="Échelle de préférence de A vers B">${left}<span class="neutral" role="img" aria-label="Point neutre non sélectionnable, bascule entre A et B"></span>${right}</div><div class="legend-grid" aria-hidden="true"><span>Forte</span><span>Moyenne</span><span>Légère</span><span class="switch">Point<br>neutre</span><span>Légère</span><span>Moyenne</span><span>Forte</span></div><div class="preference-labels"><span>Préférence A</span><span>Préférence B</span></div></div><div class="value">Sélectionnez une position</div></div>`;b.appendChild(a)});b.addEventListener('click',choose);b.addEventListener('keydown',keyboard);$('#identity').oninput=save;$('#resultBtn').onclick=results;$('#resetBtn').onclick=reset;$('#printBtn').onclick=()=>print();$('#pdfBtn').onclick=pdf}
function dot(i,v,q){const intensity=v===1||v===6?'forte':v===2||v===5?'moyenne':'légère',pref=v<=3?'A':'B';return `<button type="button" class="dot" data-i="${i}" data-v="${v}" aria-label="Préférence ${pref}, intensité ${intensity}, question ${q}" aria-pressed="false"></button>`}
function choose(e){const x=e.target.closest('.dot');if(x)select(+x.dataset.i,+x.dataset.v,true)}
function keyboard(e){const x=e.target.closest('.dot');if(!x||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const i=+x.dataset.i,v=+x.dataset.v,n=Math.max(1,Math.min(6,v+(e.key==='ArrowRight'?1:-1)));document.querySelector(`.dot[data-i="${i}"][data-v="${n}"]`).focus();select(i,n,true)}
function select(i,v,persist){S.a[i]=v;const card=$('#q'+S.c.questions[i].id);card.querySelectorAll('.dot').forEach(d=>{const on=+d.dataset.v===v;d.classList.toggle('selected',on);d.setAttribute('aria-pressed',on)});card.classList.add('answered');card.querySelector('.badge').textContent='Répondu';card.querySelector('.value').textContent='Choix enregistré';progress();if(persist)save()}
function progress(){const n=S.a.filter(Number.isInteger).length;$('#progressText').textContent=`${n} / ${S.a.length} réponses`;$('#progressFill').style.width=100*n/S.a.length+'%'}
function save(){localStorage.setItem('profilCouleursV23',JSON.stringify({id:$('#identity').value,a:S.a}))}
function restore(){try{const d=JSON.parse(localStorage.getItem('profilCouleursV23'));if(!d)return;$('#identity').value=d.id||'';(d.a||[]).forEach((v,i)=>{if(Number.isInteger(v)&&v>=1&&v<=6)select(i,v,false)})}catch(e){}}
function calc(){const s={Rouge:0,Jaune:0,Vert:0,Bleu:0},z=S.c.scale;S.c.questions.forEach((q,i)=>{const v=S.a[i];if(v<=3)s[q.left.color]+=z.leftPoints[v];else s[q.right.color]+=z.rightPoints[v]});return s}
function results(){const m=S.a.map((v,i)=>v===null?i+1:null).filter(Boolean);if(m.length){err('Veuillez répondre aux questions : '+m.join(', '));$('#q'+m[0]).scrollIntoView({behavior:'smooth'});return}$('#error').style.display='none';const s=S.scores=calc(),t=Object.values(s).reduce((a,b)=>a+b),r=Object.entries(s).sort((a,b)=>b[1]-a[1]);$('#resultIdentity').textContent=$('#identity').value?'Profil de '+$('#identity').value:'Profil anonyme';$('#dominance').innerHTML=`Dominante : <strong style="color:${hex[r[0][0]]}">${r[0][0]}</strong> · Secondaire : <strong style="color:${hex[r[1][0]]}">${r[1][0]}</strong>`;$('#scoreGrid').innerHTML=Object.keys(s).map(k=>`<div class="score ${k}"><span>${k}</span><strong>${s[k]}</strong><small>${(100*s[k]/t).toFixed(1).replace('.',',')} %</small></div>`).join('');$('#readingText').textContent=`Le profil fait ressortir une préférence dominante ${r[0][0]} et une tendance secondaire ${r[1][0]}. L’écart est de ${r[0][1]-r[1][1]} point(s).`;radar(s);$('#results').style.display='block';$('#results').scrollIntoView({behavior:'smooth'})}
function radar(s){const c=$('#radar'),x=c.getContext('2d'),L=Object.keys(s),cx=350,cy=350,R=235;const maxScore=Math.max(...Object.values(s));const axisMax=Math.max(10,Math.ceil(maxScore/5)*5);x.clearRect(0,0,c.width,c.height);x.font='bold 22px Segoe UI';x.textAlign='center';x.textBaseline='middle';for(let z=1;z<=5;z++){x.beginPath();L.forEach((_,i)=>{const a=-Math.PI/2+i*Math.PI/2,r=R*z/5,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.strokeStyle='#dbe4ee';x.lineWidth=1;x.stroke();x.fillStyle='#7a8795';x.font='12px Segoe UI';x.fillText(String(Math.round(axisMax*z/5)),cx+8,cy-r+10)}L.forEach((l,i)=>{const a=-Math.PI/2+i*Math.PI/2;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);x.strokeStyle='#c8d2de';x.stroke();x.fillStyle=hex[l];x.font='bold 22px Segoe UI';x.fillText(l,cx+Math.cos(a)*(R+48),cy+Math.sin(a)*(R+48))});x.beginPath();L.forEach((l,i)=>{const a=-Math.PI/2+i*Math.PI/2,r=R*s[l]/axisMax,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.fillStyle='#2563eb3d';x.fill();x.strokeStyle='#2563eb';x.lineWidth=5;x.stroke();L.forEach((l,i)=>{const a=-Math.PI/2+i*Math.PI/2,r=R*s[l]/axisMax;x.beginPath();x.arc(cx+Math.cos(a)*r,cy+Math.sin(a)*r,7,0,Math.PI*2);x.fillStyle=hex[l];x.fill();x.strokeStyle='#fff';x.lineWidth=2;x.stroke()})}
function pdf(){if(!S.scores)return err('Affichez d’abord votre profil.');if(!window.jspdf)return err('Le module PDF est indisponible. Vérifiez votre connexion.');const{jsPDF}=window.jspdf,d=new jsPDF(),n=$('#identity').value.trim()||'Anonyme',s=S.scores,t=Object.values(s).reduce((a,b)=>a+b),r=Object.entries(s).sort((a,b)=>b[1]-a[1]);d.setFillColor(23,50,77);d.rect(0,0,210,33,'F');d.setTextColor(255);d.setFontSize(20);d.text('Profil de management par les couleurs',105,15,{align:'center'});d.setFontSize(11);d.text('Participant : '+n,105,24,{align:'center'});d.setTextColor(30);d.setFontSize(14);d.text(`Dominante : ${r[0][0]} | Secondaire : ${r[1][0]}`,20,47);let y=62;Object.entries(s).forEach(([k,v])=>{d.text(`${k} : ${v} (${(100*v/t).toFixed(1)} %)`,20,y);y+=10});d.addImage($('#radar').toDataURL(),'PNG',72,52,120,120);d.setFontSize(9);d.text(d.splitTextToSize('Outil pédagogique inspiré du modèle DISC. Il ne constitue ni un diagnostic psychologique ni un test psychométrique validé.',170),20,190);d.save('profil-couleurs-'+n.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.pdf')}
function reset(){if(confirm('Réinitialiser toutes les réponses ?')){localStorage.removeItem('profilCouleursV23');location.reload()}}
function err(m){$('#error').textContent=m;$('#error').style.display='block'}init();